# encoding: utf-8
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe LugaresController do    
  describe "GET index vacio" do
    before(:each) do
      @lugar = Factory.build(:lugar)
      @params = {"nombre" => 'Daikoku', "detalles" => "No hay"}
    end
    
    it "asigna un conjunto de lugares a @lugares con paginacion" do
      Lugar.should_receive(:paginate).with(:page => 1, :order => "created_at DESC") { [@lugar] }
      
      get :index, :page => 1
      assigns(:lugares).should == [@lugar]
    end
    
    it "despliega el template index" do
      Lugar.stub(:paginate) { [@lugar] }
      
      get :index
      response.should render_template("index")
    end
  end
end
